/**
 * File Generated by Sideko (sideko.dev)
 */
import Client from "@public/visa_subscription_manager";

// test client mehtods (keep comment for code generation)

describe("tests client.cofdsWeb.v1.datainfo.merchants.create", () => {
  test.concurrent("200 generated_success_matching_data_found", async () => {
    // Generated success test for Matching Data Found body example from OpenAPI
    const client = new Client({
      baseUrl:
        "https://api.sideko.dev/v1/mock/public/visa-subscription-manager/0.1.0",
    });
    const response = await client.cofdsWeb.v1.datainfo.merchants.create({
      mrchRef: "string",
      data: {
        requestData: { pAN: "4072202010000000" },
        requestHeader: {
          messageDateTime: "2023-08-07 09:29:06.140",
          requestMessageId: "6da6b8b024532a2e0eacb1af58581",
        },
      },
    });
    console.log(response);
  });
  test.concurrent("200 generated_success_no_matching_data", async () => {
    // Generated success test for No Matching Data body example from OpenAPI
    const client = new Client({
      baseUrl:
        "https://api.sideko.dev/v1/mock/public/visa-subscription-manager/0.1.0",
    });
    const response = await client.cofdsWeb.v1.datainfo.merchants.create({
      mrchRef: "string",
      data: {
        requestData: { pAN: "4072202010000000" },
        requestHeader: {
          messageDateTime: "2023-08-07 09:29:06.140",
          requestMessageId: "6da6b8b024532a2e0eacb1af58581",
        },
      },
    });
    console.log(response);
  });
});
