/**
 * File Generated by Sideko (sideko.dev)
 */
import Client from "@public/visa_subscription_manager";

describe("init client", () => {
  test.concurrent("tests initializing client with all available auths", () => {
    // test init client (keep comment for code generation)
    new Client({
      baseUrl:
        "https://api.sideko.dev/v1/mock/public/visa-subscription-manager/0.1.0",
    });
  });
});

// test client mehtods (keep comment for code generation)
