/**
 * File Generated by Sideko (sideko.dev)
 */
import Client from "@public/visa_subscription_manager";

// test client mehtods (keep comment for code generation)

describe("tests client.vsps.cancel.create", () => {
  test.concurrent("200 generated_success_cancel_s1", async () => {
    // Generated success test for cancel_s1 body example from OpenAPI
    const client = new Client({
      baseUrl:
        "https://api.sideko.dev/v1/mock/public/visa-subscription-manager/0.1.0",
    });
    const response = await client.vsps.cancel.create({
      clientId: "string",
      data: { cancelStopInstructions: ["1234568", "1023000"] },
    });
    console.log(response);
  });
  test.concurrent("200 generated_success_cancel_s2", async () => {
    // Generated success test for cancel_s2 body example from OpenAPI
    const client = new Client({
      baseUrl:
        "https://api.sideko.dev/v1/mock/public/visa-subscription-manager/0.1.0",
    });
    const response = await client.vsps.cancel.create({
      clientId: "string",
      data: { cancelStopInstructions: ["1234569", "1093423"] },
    });
    console.log(response);
  });
  test.concurrent("200 generated_success_cancel_s3", async () => {
    // Generated success test for cancel_s3 body example from OpenAPI
    const client = new Client({
      baseUrl:
        "https://api.sideko.dev/v1/mock/public/visa-subscription-manager/0.1.0",
    });
    const response = await client.vsps.cancel.create({
      clientId: "string",
      data: { cancelStopInstructions: ["100"] },
    });
    console.log(response);
  });
  test.concurrent("200 generated_success_cancel_s4", async () => {
    // Generated success test for cancel_s4 body example from OpenAPI
    const client = new Client({
      baseUrl:
        "https://api.sideko.dev/v1/mock/public/visa-subscription-manager/0.1.0",
    });
    const response = await client.vsps.cancel.create({
      clientId: "string",
      data: { cancelStopInstructions: ["1234567"] },
    });
    console.log(response);
  });
  test.concurrent("200 generated_success_cancel_s5", async () => {
    // Generated success test for cancel_s5 body example from OpenAPI
    const client = new Client({
      baseUrl:
        "https://api.sideko.dev/v1/mock/public/visa-subscription-manager/0.1.0",
    });
    const response = await client.vsps.cancel.create({
      clientId: "string",
      data: { cancelStopInstructions: ["987654321"] },
    });
    console.log(response);
  });
});
