/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/visa_subscription_manager/types";

export type Additional = {
  additionalNotes?: string;
  paymentFrequency?: types.AdditionalPaymentFrequencyEnum;
};
