/**
 * File Generated by Sideko (sideko.dev)
 */

export enum AdditionalPaymentFrequencyEnum {
  Annual = "Annual",
  Biannual = "Biannual",
  Monthly = "Monthly",
  OneOff = "One off",
  Other = "Other",
  Quarterly = "Quarterly",
  Weekly = "Weekly",
}
