/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/visa_subscription_manager/types";

export type ApiMerchantStopInstruction = {
  cardAcceptorId?: string;
  conflictingStopInstructionId?: string;
  merchantName?: string;
  paymentFacilitator?: types.PaymentFacilitator;
  result: types.StopInstructionResult;
  stopInstructionId?: string;
};
