/**
 * File Generated by Sideko (sideko.dev)
 */

export enum AuditInfoLastUpdateChannelEnum {
  Api = "API",
  BatchBulk = "Batch/Bulk",
  System = "System",
  UserInterface = "User Interface",
  Vau = "VAU",
}
