/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/visa_subscription_manager/types";

export type AuditInfo = {
  cancellationDateTime?: string;
  cancelledByUser?: string;
  createdByUser: string;
  creationDateTime: string;
  extendedByUser?: string;
  extendedDateTime?: string;
  lastUpdateChannel: types.AuditInfoLastUpdateChannelEnum;
  originChannel: types.AuditInfoOriginChannelEnum;
  updatedByUser: string;
  updatedDateTime: string;
};
