/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/visa_subscription_manager/types";

export type MerchantDataResponse = {
  responseData?: types.MResponseData;
  responseHeader: any;
  status: types.Status;
};
