/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/visa_subscription_manager/types";

export type Merchant = {
  acctNumOld4Digit: string;
  cardAcceptorId: string;
  confidenceInd: string;
  lastMrchTranDt: string;
  lastTranAmt: string;
  lastTranAmtBillCurrency?: string;
  lastTranAmtUSD?: string;
  lastTranBillCurrency?: string;
  lastTranCurrency?: string;
  lastTranDateTime?: string;
  mCC: string;
  mrchAddr: string;
  mrchDbaId: string;
  mrchDbaName: string;
  mrchName: string;
  mrchPhoneNum: string;
  mrchRef: string;
  mrchURL: string;
  paymentFacilitatorId?: string;
  sponsoredMerchantId?: string;
  tokenPANReplacementDate: string;
  tokenPANReplacementStatus: string;
  tokenReqstrId: string;
  totalTranCount: string;
  tranTypeDetails?: types.TranType[];
  vAULastUpdateDate: string;
  vAUUpdateStatus: string;
};
