/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/visa_subscription_manager/types";

export type MerchantIdentifierDetail = {
  cardAcceptorId?: string;
  merchantCategoryCode?: string;
  merchantName?: string;
  paymentFacilitator?: types.PaymentFacilitator;
};
