/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/visa_subscription_manager/types";

export type MerchantIdentifiersWithGrouping = {
  cardAcceptorIds?: string[];
  grouped?: types.MerchantIdentifier[];
  merchantNames?: string[];
  paymentFacilitators?: types.PaymentFacilitator[];
};
