/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/visa_subscription_manager/types";

export type PanData = {
  merchants?: types.Merchant[];
  pAN: string;
  panResponseMsg: string;
};
