/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/visa_subscription_manager/types";

export type RawMerchantDataRequest = {
  requestData: types.RmRequestData;
  requestHeader: types.RequestHeader;
};
