/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/visa_subscription_manager/types";

export type RawMerchantDataResponse = {
  responseData?: types.RmResponseData;
  responseHeader: any;
  status: types.Status;
};
