/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/visa_subscription_manager/types";

export type SearchStopsApiRsp = {
  result: types.StopInstructionResult;
  searchedStopInstructions: types.StopInstructionDetail[];
};
