/**
 * File Generated by Sideko (sideko.dev)
 */

export enum StopInstructionDetailStatusEnum {
  Active = "Active",
  Cancelled = "Cancelled",
  Expired = "Expired",
  Pending = "Pending",
  Unknown = "Unknown",
}
