/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/visa_subscription_manager/types";

export type StopInstructionDetail = {
  additional?: types.Additional;
  auditInformation: types.AuditInfo;
  endDate: string;
  merchantIdentifier?: types.MerchantIdentifierDetail;
  oneTimeStop: boolean;
  previousStopInstructionId?: string;
  recurringAndInstallmentIndicator: boolean;
  startDate: string;
  status: types.StopInstructionDetailStatusEnum;
  stopInstructionId: string;
  stopInstructionType: types.StopInstructionDetailStopInstructionTypeEnum;
  transactionAmount?: types.TransactionAmount;
};
