/**
 * File Generated by Sideko (sideko.dev)
 */

export enum TranTypeTranTypeEnum {
  ScheduledRecurringUnscheduledRecurringInstallmentMerchantCofCustomerCofUnknownCofMailTelephoneBillPayEcomOtherAuthVerification = "SCHEDULED_RECURRING, UNSCHEDULED_RECURRING, INSTALLMENT, MERCHANT_COF, CUSTOMER_COF, UNKNOWN_COF, MAIL_TELEPHONE, BILL_PAY, ECOM_OTHER, AUTH_VERIFICATION",
}
