/**
 * File Generated by Sideko (sideko.dev)
 */
import {
  CoreResourceClient,
  CoreClient,
  RequestOptions,
  ApiPromise,
} from "@public/visa_subscription_manager/core";
import { MerchantsClient } from "@public/visa_subscription_manager/resources/cofds-web/v1/datainfo/merchants";
import * as requests from "@public/visa_subscription_manager/resources/cofds-web/v1/datainfo/request-types";
import * as types from "@public/visa_subscription_manager/types";

export class DatainfoClient extends CoreResourceClient {
  // register resources (keep comment for code generation)
  merchants: MerchantsClient;

  constructor(client: CoreClient) {
    super(client);

    // init resources (keep comment for code generation)
    this.merchants = new MerchantsClient(this._client);
  }

  // register api methods (keep comment for code generation)

  /**
   * The API will return data layer aggregated at cleansed merchant name level.
   */
  create(
    request: requests.CreateRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.MerchantDataResponse> {
    // send request (keep comment for code generation)
    return this._client.makeRequest({
      method: "post",
      path: "/cofds-web/v1/datainfo",
      contentType: "application/json",
      body: request.data,
      responseType: "json",
      opts,
    });
  }
}
