/**
 * File Generated by Sideko (sideko.dev)
 */
import {
  CoreResourceClient,
  CoreClient,
} from "@public/visa_subscription_manager/core";
import { MerchantClient } from "@public/visa_subscription_manager/resources/vsps/add/merchant";

export class AddClient extends CoreResourceClient {
  // register resources (keep comment for code generation)
  merchant: MerchantClient;

  constructor(client: CoreClient) {
    super(client);

    // init resources (keep comment for code generation)
    this.merchant = new MerchantClient(this._client);
  }

  // register api methods (keep comment for code generation)
}
